DATA_URL: "https://archive.ics.uci.edu/ml/machine-learning-databases/JapaneseVowels/"


PIPELINE: # Change these for the pipeline
  TRAIN: True
  TEST: False

MAX_LEN: 29  # longest utterance length (7â€“29)
N_FEATURES: 12

AUGMENTATION:
  AUGMENT: false
  REPEATS: 100
  AUG_FILE: "data/augmented_data.npz"
  SEED: 42
  STEPS:
    - type: gaussian_noise
      noise_factor: 0.001
      p: 1.0
    - type: random_scaling
      scale_range: [0.95, 1.05]
    - type: time_masking
      max_mask_percentage: 0.01
    # - type: frequency_masking
    #   max_mask_percentage: 0.01

EMBEDDING:
  MODEL: "nomic-embed-text-v1.5"
  DIMENSION: 64
  PRE_PRECISION: 2

INPUT_DIRS:
  TRAIN_FILE: "data/ae.train"
  TEST_FILE: "data/ae.test"

OUTPUT_DIRS:
  PROCESSED: "data/processed_data"

#HAIKU
MODEL:
  NUM_CLASSES: 9
  DROPOUT: 0.3
  EMBEDDING_DIM: 64
  KERNEL_SIZE: 3
  CONV_CHANNELS: 128
  HIDDEN_DIM: 64
  INPUT_CHANNELS: 12
  LEARNING_RATE: 0.007
  BATCH_SIZE: 32
  NUM_EPOCHS: 10
  DEVICE: "cuda"  # Options: "cuda", "cpu", "auto" (auto-detect)